### ISSUE TITLE
edxposed blacklist broken

### ISSUE THREAD

**Issue by rxzcums** [BlueCat300/XposedAppSettings#1]
hi, thanks for this good module dev.

i found once install this, then the edxposed blacklist not work anymore, i don't know it's the module's bug or the edxposed's, plz check it, thank you.

another module will break edxposed's blacklist is chimi.

**Comment by BlueCat300** [comment]
It has just been tested on the AIMP (music player), Opera and it works as expected. 
Edxposed's blacklist requires, like any other module to force-stop the **process** of the target application in order to apply changes. Edxposed does not automatically stop the application process.

I can check only on my device, and this samsung with One UI on Android 10. From user reports, this module has problems with MIUI based ROMs.

**Comment by rxzcums** [comment]
yes, i'm on miui...

**Comment by rxzcums** [comment]
does it possible the blacklist function need hook some api which hooked by module too, then ...?

**Comment by BlueCat300** [comment]
https://github.com/ElderDrivers/EdXposedManager/blob/master/app/src/main/java/org/meowcat/edxposed/manager/xposed/Enhancement.java
I did not find such.  And everything works for me.  Unfortunately, I can not guarantee work on firmware not available to me.

**Comment by rxzcums** [comment]
> https://github.com/ElderDrivers/EdXposedManager/blob/master/app/src/main/java/org/meowcat/edxposed/manager/xposed/Enhancement.java
> I did not find such. And everything works for me. Unfortunately, I can not guarantee work on firmware not available to me.

thanks for your work, maybe some day in the future can fix it :)
