### ISSUE TITLE
EdExposed version recognition fails

### ISSUE THREAD

**Issue by cyko69** [BlueCat300/XposedAppSettings#6]
I am using edExposed 0.5.2.2_4683_master YAHFA.
When starting appSettings it tells me "Xposed is not activated or does not match the latest Version. Minimum Version is 0.5.1.4"

**Comment by BlueCat300** [comment]
This dialog appears only under one condition, the framework does not hook SharedPreferences module and it's throw security exception. This can only happen when the framework / module is disabled or framework is not installed correctly.
Maybe you have such a problem https://github.com/ElderDrivers/EdXposed/issues/828? If not then uninstall module -- reboot -- install module -- reboot.

**Comment by cyko69** [comment]
Module reinstall changed nothing. EdXposed Manager said that everything is fine, I switched to edXposed debug version to see  whats going on and the error was gone, switched back to release and the error is still gone. So no problem with appSettings. Thanks for your help.

**Comment by drogga** [comment]
Hi @BlueCat300, so I saw that unfortunately since v1.2^ you implemented a check for Xposed (root), there's a sense in that, but just  the thing is that I use it to list packages (it has a really good search filter that looks through the app and package name at the same time) and a list of permissions which I like and use, but that's not possible anymere, simply because it shows a message that it's not enabled in the Xposed, so would you be so kind to please get rid of that check ?
Thanks in advance ;)

**Comment by drogga** [comment]
Hi @BlueCat300, so I saw that unfortunately in \ since v1.2 (^) you implemented a check for Xposed (root) that prevents me from using the app, there's a sense in that, but just the thing is that I use it to list packages _(it has a really good search filter that looks through the app and package names at the same time)_ and shows a list of permissions which I like and use _(among other useful info and functionality)_, but that's not possible anymore, simply because it shows a message that it's not enabled in the Xposed, so would you be so kind to please get rid of that check ?, even if you don't see the point of\in doing this as the app is meant \ intended to be used as a module and can't do anything without Root & Xposed...
Thanks in advance ;)

BTW - I also don't like that the minSDKversion and the package (.apk) file size keeps increasing - from 15 [4.0.3] to 19 [4.4] and now 21 [5.0] and it used to be ~240 KB, now it's ~2.05 MB, but I can't do anything about it, other than using an older version...
And Please don't get me wrong - I don't criticize you at all.

**Comment by BlueCat300** [comment]
There were too many complaints on xda regarding the "not working" state of the module, since people simply did not understand that permissive selinux is needed to work on a framework lower than 0.5.1.3 when module have target SDK 27+
I will not be able to remove it because it will start again. Maybe I'll make it passable, but it will still always will be remind you that xposed is disabled.

minSDKversion is needed to implement a material theme, vector graphics, system file picker. In any case this is not critical on this fork, since I support only on Android 8.0+
Size is increasing due to androidx libraries.
For older versions there is a [corresponding version](https://forum.xda-developers.com/t/mod-xposed-4-0-app-settings-v1-10-2014-08-13.2437377/post-75681490)

**Comment by drogga** [comment]
Ok, please do so ASAP, also I believe there is no need for additional dialog prompt or anything, as you can just make the current msg. that it currently shows to show up only once as a dialog prompt pop-up window - at first launch\run, with a "ok", "agree" or "skip" button (as I already mentioned), it will act as ToS, you can even include\add the requirements there...

There isn't a restriction for the material theme, at least not a real\actual one, as this can be easy targeted as an exceptions in the resources > values-v21 > styles.xml, also to be honest - I don't even know or understand why you had to even "touch" the theme, as it was perfect - a native dark one on every device and OS ver. or fork (Firmware \ ROM) I tested it on, which can still be made to use "DeviceDefault" instead, so this change was unnecessary (but enforced by AndroidX), the same thing goes for the vector graphic images (older APIs have no problem with those whatsoever - AFAIK), regarding the File Picker for the "import" & "Export" functionality - can still be made to hook\handle\use SAF for API\SDK 19 [4.4] and up, "Documents UI" or whatever and an exception for lower than 4.4 KK to use whatever you have on the system (as file managers - for example, on 4.1.2 JB when it's required\needed I can pick files using couple of external apps, 2 of them are Root Explorer & ES).
You may "technically" ("on paper") work on the 8 Oreo (+) support, but that doesn't mean the the app can't\don't work, or it's completely useless on lower\older than that.
See, I hate AndroidX, you shouldn't go with \ used it (\them), as nothing good comes from it (\those), only over-complications and file size increasements. I feel like it only exists just to brake the (UI) compatibility for\with older OS vers. and nothing else as of benefits - this is my opinion on that.
Yes, I know and already use those older Modded versions \ builds ;)

BTW - I may try to do some refinements with Android Studio to see how this goes...
All the best ;)

**Comment by drogga** [comment]
### **The module is not active!**
Make sure EdXposed/LSPosed framework is installed and module enabled on EdXposed/LSPosed manager then reboot device.
**[OK]**

@BlueCat300 Hi, I saw that there's a new version, but the ^above^ message and check is still present, which unfortunately I still can't ignore...

**Comment by drogga** [comment]
> **The module is not active!**
> Make sure EdXposed/LSPosed framework is installed and module enabled on EdXposed/LSPosed manager then reboot device.
> [**OK**]

@BlueCat300 Hi, I saw that there's a new version, but the ^above^ message and check is still present, which unfortunately I still can't ignore...

**Comment by drogga** [comment]
> **The module is not active!**
> Make sure EdXposed/LSPosed framework is installed and module enabled on EdXposed/LSPosed manager then reboot device.
> [**OK**]

&

> **The module is not active!**
> The module requires permissive SELinux or EdXposed Framework minimum version0.5.1.3. Any version of LSposed will work as well.
> [**OK**]

@BlueCat300 Hi, I saw that there's a new version, but the ^above^ messages and checks are still present, which unfortunately I still can't ignore...

Anyway, I managed to 'nop' the 2 calls/checks (0x0>0x1 & 0x1>0x0) by modifying the smali, but I shouldn't have to do this as this is not the point...

**Comment by BlueCat300** [comment]
> Hi, I saw that there's a new version, but the ^above^ messages and checks are still present, which unfortunately I still can't ignore...
The module will remain an xposed module, not an app manager.  I have to be sure that the user has enabled the framework.  It won't change.  You can use the old version or create a fork.
> Also, I was told by a few developers, that the new trend is to get rid of the side swiping menus in apps, because they interfere with the navigation gestures
I like this menu more, I use it in tandem with a tablet.
